name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   # - name: Build the Docker image
      
      
    - name: Log in to GitHub Container Registry
        #echo "${{ secrets.CR_PAT }}" | docker login ghcr.io --username salmaghazal --password-stdin
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        #
    - name: Push the Docker image to the registry
      run: |
        docker build "${{ github.workspace }}/synApp" --tag ghcr.io/salmaghazal/djpgngapp1:latest
        docker push ghcr.io/salmaghazal/djpgngapp1:latest
        
