name: Docker Image CI

on:
  push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   # - name: Build the Docker image
      
      
    - name: Log in to GitHub Container Registry
        #echo "${{ secrets.CR_PAT }}" | docker login ghcr.io --username salmaghazal --password-stdin
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        #
        
    - name: Set env
      run: |
        echo "GIT_TAG=`echo $(git describe --tags --always $(git rev-list --tags --max-count=1))`" >> $GITHUB_ENV
  #
    - name: Display IMG_TAG value
      run: echo "IMG_TAG = ${{ env.IMG_TAG }}"
      
    - name: Push the Docker image to the registry
      env: 
        IMG_TAG: ${{ env.GIT_TAG }}
      run: |
        docker build "${{ github.workspace }}/synApp" --tag ghcr.io/salmaghazal/pollappimage:${{env.IMG_TAG}}
        docker push ghcr.io/salmaghazal/pollappimage:${{env.IMG_TAG}}
        
